### PR TITLE
[20230725][CMake] Detect properly new linker introduced in Xcode 15

### PR DESCRIPTION
**Pull request by edymtt**
As explained in [1], this linker is functionally equivalent to the classic one (`ld64`) for build system purposes -- in particular to enable the use of order files to link `clang`. For this reason, in addition to fixing the detection rename `LLVM_LINKER_IS_LD64` to `LLVM_LINKER_IS_APPLE` to make the result of such detection more clear -- this should not cause any issue to downstream users, from a quick search in SourceGraph [2], only Swift uses the value of this variable (which I will take care of updating in due time).

[1]: https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Linking
[2]: https://sourcegraph.com/search?q=context:global+LLVM_LINKER_IS_LD64+lang:cmake+fork:no+-file:AddLLVM.cmake+-file:clang/tools/driver/CMakeLists.txt&patternType=standard&sm=1&groupBy=repo
rdar://120740222

(cherry picked from commit 9175dd9cbcad01a47acea9f1b99a0c96bf1a9a29)

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please test

**Comment by edymtt** [comment]
@swift-ci test llvm

**Review by ldionne — APPROVED** [review]

**Comment by edymtt** [comment]
LLVM macOS job has one test failures that matches the ones in #7919 (a previous PR for `stable/20230725` that tested LLVM)

```
Failed Tests (1):
  LLVM :: Instrumentation/AddressSanitizer/global_with_comdat.ll
```

The linux one has 220 failures, which I don't see in #7919 -- not positive this depends on this changes (since I had no regression when testing on LLVM buildkite), errors seem all related to finding modules

```
/home/build-user/llvm-project/clang/test/CXX/module/module.interface/p2.cpp:23:15: fatal error: error in loading module 'X' from prebuilt module path
   23 | export import X;
      |               ^
1 error generated.
```

**Comment by edymtt** [comment]
@swift-ci test llvm Linux

**Comment by edymtt** [comment]
In the second Linux run I have the exact failures as #7919 

```
Failed Tests (2):
  Clang :: ClangScanDeps/modules-include-tree-prefix-map.c
  LLVM :: Instrumentation/AddressSanitizer/global_with_comdat.ll
```

So likely I hit some transient failure.
